version: 0.2
phases:
  install:
    commands:
      - npm i # https://github.com/awslabs/serverless-application-model/issues/93
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket wallets-lambda --s3-prefix polo-wallet-monitor-test --output-template-file packaged-sam.yml
  post_build:
		commands:
      - aws cloudformation deploy --template-file packaged-sam.yml --stack-name polo-wallet-monitor-test --capabilities CAPABILITY_IAM

